parameters:
    ifgm_acl_interface.config_manager_chain.class: Ifgm\ACLInterfaceBundle\Manager\ConfigManagerChain
    ifgm_acl_interface.config_manager.class: Ifgm\ACLInterfaceBundle\Manager\ConfigManager

services:

    ifgm_acl_interface.config_manager_chain:
        class: %ifgm_acl_interface.config_manager_chain.class%

    ifgm_acl_interface.form_manager:
        class: %ifgm_acl_interface.form_manager.class%

    ifgm.acl_manager:
        class: Ifgm\ACLInterfaceBundle\Manager\AclManager
        arguments:
            - @request
            - @templating
            - @form.factory
            - @ifgm_acl_interface.config_manager_chain
            - @doctrine.orm.entity_manager
            - %ifgm_acl_interface.acl.class%
            - %ifgm_acl_interface.user.class%
            - %ifgm_acl_interface.mask_builder.class%
        scope: request

    ifgm_acl_interface.permission_map:
        class: %ifgm_acl_interface.permission_map.class%
        public: false

    ifgm_acl_interface.acl_voter:
        class:      %ifgm_acl_interface.acl_voter.class%
        arguments:
          - @doctrine.orm.entity_manager
          - @ifgm_acl_interface.permission_map
          - %ifgm_acl_interface.acl.class%
          - %ifgm_acl_interface.mask_builder.class%
        public:     false
        tags:
            - { name: security.voter }
